// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameUserInfo = "tb_user_info"

// UserInfo mapped from table <tb_user_info>
type UserInfo struct {
	UserID     int64      `gorm:"column:user_id;primaryKey;comment:主键，用户id" json:"user_id"`                                               // 主键，用户id
	City       *string    `gorm:"column:city;comment:城市名称" json:"city"`                                                                   // 城市名称
	Introduce  *string    `gorm:"column:introduce;comment:个人介绍，不要超过128个字符" json:"introduce"`                                              // 个人介绍，不要超过128个字符
	Fans       *int32     `gorm:"column:fans;comment:粉丝数量" json:"fans"`                                                                   // 粉丝数量
	Followee   *int32     `gorm:"column:followee;comment:关注的人的数量" json:"followee"`                                                        // 关注的人的数量
	Gender     *bool      `gorm:"column:gender;comment:性别，0：男，1：女" json:"gender"`                                                         // 性别，0：男，1：女
	Birthday   *time.Time `gorm:"column:birthday;comment:生日" json:"birthday"`                                                             // 生日
	Credits    *int32     `gorm:"column:credits;comment:积分" json:"credits"`                                                               // 积分
	Level      *bool      `gorm:"column:level;comment:会员级别，0~9级,0代表未开通会员" json:"level"`                                                   // 会员级别，0~9级,0代表未开通会员
	CreateTime time.Time  `gorm:"column:create_time;not null;default:current_timestamp();autoCreateTime;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time  `gorm:"column:update_time;not null;default:current_timestamp();autoUpdateTime;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName UserInfo's table name
func (*UserInfo) TableName() string {
	return TableNameUserInfo
}
