// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go-dianping/internal/handler"
	"go-dianping/internal/repository"
	"go-dianping/internal/server"
	"go-dianping/internal/service"
	"go-dianping/pkg/log"
	"go-dianping/pkg/redis"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	client := redis.NewRedis(viperViper)
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger, client)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	shopTypeRepository := repository.NewShopTypeRepository(repositoryRepository)
	shopTypeService := service.NewShopTypeService(serviceService, shopTypeRepository)
	shopTypeHandler := handler.NewShopTypeHandler(handlerHandler, shopTypeService)
	engine := server.NewHttpServer(client, userHandler, shopTypeHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(redis.NewRedis, server.NewHttpServer)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository, repository.NewShopTypeRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewShopTypeService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewShopTypeHandler)
