// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go-dianping/internal/base/cache_client"
	"go-dianping/internal/base/redis_worker"
	"go-dianping/internal/handler"
	"go-dianping/internal/server"
	"go-dianping/internal/service"
	"go-dianping/pkg/app"
	"go-dianping/pkg/log"
	"go-dianping/pkg/redis"
	"go-dianping/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	client := redis.NewRedis(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := service.NewDB(viperViper, logger)
	query := service.NewQuery(db)
	serviceService := service.NewService(logger, viperViper, query, client)
	cacheClient := cache_client.NewCacheClientForShop(client)
	shopService := service.NewShopService(serviceService, cacheClient)
	shopHandler := handler.NewShopHandler(handlerHandler, shopService)
	shopTypeService := service.NewShopTypeService(serviceService)
	shopTypeHandler := handler.NewShopTypeHandler(handlerHandler, shopTypeService)
	userService := service.NewUserService(serviceService)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	voucherService := service.NewVoucherService(serviceService)
	voucherHandler := handler.NewVoucherHandler(handlerHandler, voucherService)
	redisWorker := redis_worker.NewRedisWorker(client)
	voucherOrderService := service.NewVoucherOrderService(serviceService, redisWorker)
	voucherOrderHandler := handler.NewVoucherOrderHandler(handlerHandler, voucherOrderService)
	httpServer := server.NewHTTPServer(logger, viperViper, client, shopHandler, shopTypeHandler, userHandler, voucherHandler, voucherOrderHandler)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var cacheClientSet = wire.NewSet(cache_client.NewCacheClientForShop)

var redisWorkerSet = wire.NewSet(redis_worker.NewRedisWorker)

var serviceSet = wire.NewSet(service.NewDB, service.NewQuery, service.NewService, service.NewSeckillVoucherService, service.NewShopService, service.NewShopTypeService, service.NewUserService, service.NewVoucherService, service.NewVoucherOrderService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewShopHandler, handler.NewShopTypeHandler, handler.NewUserHandler, handler.NewVoucherHandler, handler.NewVoucherOrderHandler)

var serverSet = wire.NewSet(redis.NewRedis, server.NewHTTPServer)

// build App
func newApp(
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("go-dianping"))
}
