// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "llmons",
            "url": "https://github.com/llmons",
            "email": "llmons@foxmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shop": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "更新商铺",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/shop-type/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop-type"
                ],
                "summary": "获取商品类别列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.GetShopTypeListResp"
                        }
                    }
                }
            }
        },
        "/shop/:id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "根据 id 获取商铺",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.GetShopByIdResp"
                        }
                    }
                }
            }
        },
        "/user/code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.LoginResp"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前登录的用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.GetMeResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-dianping_api_v1.GetMeResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.GetMeRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.GetMeRespData": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "go-dianping_api_v1.GetShopByIdResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.GetShopByIdRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.GetShopByIdRespData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "area": {
                    "type": "string"
                },
                "avgPrice": {
                    "type": "integer"
                },
                "comments": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "openHours": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "sold": {
                    "type": "integer"
                },
                "typeId": {
                    "type": "integer"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "go-dianping_api_v1.GetShopTypeListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-dianping_api_v1.GetShopTypeListRespDataItem"
                    }
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.GetShopTypeListRespDataItem": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.LoginResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.LoginRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.LoginRespData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "go-dianping_api_v1.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Go Dian Ping",
	Description:      "hmdp implemented by go",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
