// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "llmons",
            "url": "https://github.com/llmons",
            "email": "llmons@foxmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shop": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "更新商铺信息",
                "parameters": [
                    {
                        "description": "商铺数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.UpdateShopReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/shop-type/list": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop-type"
                ],
                "summary": "获取商品类别列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.QueryTypeListResp"
                        }
                    }
                }
            }
        },
        "/shop/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "根据 id 查询商铺信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商铺 id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.QueryShopByIDResp"
                        }
                    }
                }
            }
        },
        "/user/code": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "发送短信验证码并保存验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "实现登录功能",
                "parameters": [
                    {
                        "description": "登录请求体",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.LoginResp"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "获取当前登录的用户并返回",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/go-dianping_api_v1.MeResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-dianping_api_v1.LoginReq": {
            "type": "object",
            "required": [
                "code",
                "phone"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "password": {
                    "type": "string",
                    "example": ""
                },
                "phone": {
                    "type": "string",
                    "example": "13456789001"
                }
            }
        },
        "go-dianping_api_v1.LoginResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.LoginRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.LoginRespData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "go-dianping_api_v1.MeResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.MeRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.MeRespData": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "go-dianping_api_v1.QueryShopByIDResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/go-dianping_api_v1.QueryShopByIDRespData"
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.QueryShopByIDRespData": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "area": {
                    "description": "商圈，例如陆家嘴",
                    "type": "string"
                },
                "avg_price": {
                    "description": "均价，取整数",
                    "type": "integer"
                },
                "comments": {
                    "description": "评论数量",
                    "type": "integer"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "images": {
                    "description": "商铺图片，多个图片以','隔开",
                    "type": "string"
                },
                "name": {
                    "description": "商铺名称",
                    "type": "string"
                },
                "open_hours": {
                    "description": "营业时间，例如 10:00-22:00",
                    "type": "string"
                },
                "score": {
                    "description": "评分，1~5分，乘10保存，避免小数",
                    "type": "integer"
                },
                "sold": {
                    "description": "销量",
                    "type": "integer"
                },
                "type_id": {
                    "description": "商铺类型的id",
                    "type": "integer"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                },
                "x": {
                    "description": "经度",
                    "type": "number"
                },
                "y": {
                    "description": "维度",
                    "type": "number"
                }
            }
        },
        "go-dianping_api_v1.QueryTypeListResp": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-dianping_api_v1.QueryTypeListRespDataItem"
                    }
                },
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.QueryTypeListRespDataItem": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sort": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errorMsg": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "go-dianping_api_v1.UpdateShopReq": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "金华路锦昌文华苑29号"
                },
                "area": {
                    "type": "string",
                    "example": "大关"
                },
                "avgPrice": {
                    "type": "integer",
                    "example": 80
                },
                "comments": {
                    "type": "integer",
                    "example": 3035
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "images": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": "120茶餐厅"
                },
                "openHours": {
                    "type": "string",
                    "example": "10:00-22:00"
                },
                "score": {
                    "type": "integer",
                    "example": 37
                },
                "sold": {
                    "type": "integer",
                    "example": 4215
                },
                "typeId": {
                    "type": "integer",
                    "example": 1
                },
                "x": {
                    "type": "number",
                    "example": 0
                },
                "y": {
                    "type": "number",
                    "example": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8081",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Go Dian Ping",
	Description:      "golang 实现的黑马点评",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
