definitions:
  go-dianping_api_v1.GetMeResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.GetMeRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.GetMeRespData:
    properties:
      icon:
        type: string
      id:
        type: integer
      nickname:
        type: string
    type: object
  go-dianping_api_v1.GetShopByIdResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.GetShopByIdRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.GetShopByIdRespData:
    properties:
      address:
        type: string
      area:
        type: string
      avgPrice:
        type: integer
      comments:
        type: integer
      id:
        type: integer
      images:
        type: string
      name:
        type: string
      openHours:
        type: string
      score:
        type: integer
      sold:
        type: integer
      typeId:
        type: integer
      x:
        type: number
      "y":
        type: number
    type: object
  go-dianping_api_v1.GetShopTypeListResp:
    properties:
      data:
        items:
          $ref: '#/definitions/go-dianping_api_v1.GetShopTypeListRespDataItem'
        type: array
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.GetShopTypeListRespDataItem:
    properties:
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      sort:
        type: integer
    type: object
  go-dianping_api_v1.LoginResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.LoginRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.LoginRespData:
    properties:
      token:
        type: string
    type: object
  go-dianping_api_v1.Response:
    properties:
      data: {}
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
host: localhost:8081
info:
  contact:
    email: llmons@foxmail.com
    name: llmons
    url: https://github.com/llmons
  description: hmdp implemented by go
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Dian Ping
  version: 1.0.0
paths:
  /shop:
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.Response'
      summary: 更新商铺
      tags:
      - shop
  /shop-type/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.GetShopTypeListResp'
      summary: 获取商品类别列表
      tags:
      - shop-type
  /shop/:id:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.GetShopByIdResp'
      summary: 根据 id 获取商铺
      tags:
      - shop
  /user/code:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.Response'
      summary: 发送验证码
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.LoginResp'
      summary: 登录
      tags:
      - user
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.GetMeResp'
      security:
      - Bearer: []
      summary: 获取当前登录的用户信息
      tags:
      - user
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
