definitions:
  go-dianping_api_v1.GetMeResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.GetMeRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.GetMeRespData:
    properties:
      icon:
        type: string
      id:
        type: integer
      nickname:
        type: string
    type: object
  go-dianping_api_v1.GetShopByIDResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.GetShopByIDRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.GetShopByIDRespData:
    properties:
      address:
        description: 地址
        type: string
      area:
        description: 商圈，例如陆家嘴
        type: string
      avg_price:
        description: 均价，取整数
        type: integer
      comments:
        description: 评论数量
        type: integer
      create_time:
        description: 创建时间
        type: string
      id:
        description: 主键
        type: integer
      images:
        description: 商铺图片，多个图片以','隔开
        type: string
      name:
        description: 商铺名称
        type: string
      open_hours:
        description: 营业时间，例如 10:00-22:00
        type: string
      score:
        description: 评分，1~5分，乘10保存，避免小数
        type: integer
      sold:
        description: 销量
        type: integer
      type_id:
        description: 商铺类型的id
        type: integer
      update_time:
        description: 更新时间
        type: string
      x:
        description: 经度
        type: number
      "y":
        description: 维度
        type: number
    type: object
  go-dianping_api_v1.LoginReq:
    properties:
      code:
        example: "123456"
        type: string
      password:
        example: ""
        type: string
      phone:
        example: "13456789001"
        type: string
    required:
    - code
    - phone
    type: object
  go-dianping_api_v1.LoginResp:
    properties:
      data:
        $ref: '#/definitions/go-dianping_api_v1.LoginRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.LoginRespData:
    properties:
      token:
        type: string
    type: object
  go-dianping_api_v1.QueryTypeListResp:
    properties:
      data:
        items:
          $ref: '#/definitions/go-dianping_api_v1.QueryTypeListRespDataItem'
        type: array
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  go-dianping_api_v1.QueryTypeListRespDataItem:
    properties:
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      sort:
        type: integer
    type: object
  go-dianping_api_v1.Response:
    properties:
      data: {}
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
host: localhost:8081
info:
  contact:
    email: llmons@foxmail.com
    name: llmons
    url: https://github.com/llmons
  description: golang 实现的黑马点评
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Dian Ping
  version: 1.0.0
paths:
  /shop:
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.Response'
      summary: 更新商铺
      tags:
      - shop
  /shop-type/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.QueryTypeListResp'
      summary: 获取商品类别列表
      tags:
      - shop-type
  /shop/:id:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.GetShopByIDResp'
      summary: 根据 id 获取商铺
      tags:
      - shop
  /user/code:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.Response'
      summary: 发送验证码
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/go-dianping_api_v1.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.LoginResp'
      summary: 登录
      tags:
      - user
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-dianping_api_v1.GetMeResp'
      security:
      - Bearer: []
      summary: 获取当前登录的用户信息
      tags:
      - user
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
