definitions:
  model.Shop:
    properties:
      address:
        description: 地址
        type: string
      area:
        description: 商圈，例如陆家嘴
        type: string
      avgPrice:
        description: 均价，取整数
        type: integer
      comments:
        description: 评论数量
        type: integer
      id:
        description: 主键
        type: integer
      images:
        description: 商铺图片，多个图片以','隔开
        type: string
      name:
        description: 商铺名称
        type: string
      openHours:
        description: 营业时间，例如 10:00-22:00
        type: string
      score:
        description: 评分，1~5分，乘10保存，避免小数
        type: integer
      sold:
        description: 销量
        type: integer
      typeId:
        description: 商铺类型的id
        type: integer
      x:
        description: 经度
        type: number
      "y":
        description: 维度
        type: number
    type: object
  model.User:
    properties:
      icon:
        description: 人物头像
        type: string
      id:
        description: 主键
        type: integer
      nickName:
        description: 昵称，默认是用户id
        type: string
      password:
        description: 密码，加密存储
        type: string
      phone:
        description: 手机号码
        type: string
    type: object
  model.Voucher:
    properties:
      actualValue:
        description: 抵扣金额，单位是分。例如200代表2元
        type: integer
      beginTime:
        type: string
      endTime:
        type: string
      id:
        description: 主键
        type: integer
      payValue:
        description: 支付金额，单位是分。例如200代表2元
        type: integer
      rules:
        description: 使用规则
        type: string
      shopId:
        description: 商铺id
        type: integer
      status:
        description: 1,上架; 2,下架; 3,过期
        type: integer
      stock:
        type: integer
      subTitle:
        description: 副标题
        type: string
      title:
        description: 代金券标题
        type: string
      type:
        description: 0,普通券；1,秒杀券
        type: integer
    type: object
  v1.AddSeckillVoucherResp:
    properties:
      data:
        $ref: '#/definitions/v1.AddSeckillVoucherRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.AddSeckillVoucherRespData:
    properties:
      id:
        type: integer
    type: object
  v1.AddVoucherResp:
    properties:
      data:
        $ref: '#/definitions/v1.AddVoucherRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.AddVoucherRespData:
    properties:
      id:
        type: integer
    type: object
  v1.LoginReq:
    properties:
      code:
        example: "123456"
        type: string
      password:
        example: ""
        type: string
      phone:
        example: "13456789001"
        type: string
    required:
    - code
    - phone
    type: object
  v1.LoginResp:
    properties:
      data:
        $ref: '#/definitions/v1.LoginRespData'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.LoginRespData:
    properties:
      token:
        type: string
    type: object
  v1.MeResp:
    properties:
      data:
        $ref: '#/definitions/v1.SimpleUser'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.QueryShopByIDResp:
    properties:
      data:
        $ref: '#/definitions/model.Shop'
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.QueryTypeListResp:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.QueryVoucherOfShopResp:
    properties:
      data:
        items:
          $ref: '#/definitions/model.Voucher'
        type: array
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.Response:
    properties:
      data: {}
      errorMsg:
        type: string
      success:
        type: boolean
      total:
        type: integer
    type: object
  v1.SimpleUser:
    properties:
      icon:
        type: string
      id:
        type: integer
      nickName:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: llmons@foxmail.com
    name: llmons
    url: https://github.com/llmons
  description: golang 实现的黑马点评
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Dian Ping
  version: 1.0.0
paths:
  /api/shop:
    put:
      consumes:
      - application/json
      parameters:
      - description: 商铺数据
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Shop'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: 更新商铺信息
      tags:
      - shop
  /shop-type/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.QueryTypeListResp'
      summary: 获取商品类别列表
      tags:
      - shop-type
  /shop/{id}:
    get:
      parameters:
      - description: 商铺 id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.QueryShopByIDResp'
      summary: 根据 id 查询商铺信息
      tags:
      - shop
  /user/code:
    post:
      parameters:
      - description: 手机号
        in: query
        name: phone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: 发送短信验证码并保存验证码
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录请求体
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.LoginResp'
      summary: 实现登录功能
      tags:
      - user
  /user/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.MeResp'
      security:
      - Bearer: []
      summary: 获取当前登录的用户并返回
      tags:
      - user
  /voucher:
    post:
      consumes:
      - application/json
      parameters:
      - description: 优惠券信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Voucher'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.AddVoucherResp'
      summary: 新增普通券
      tags:
      - voucher
  /voucher/list/{shopId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 商铺 id
        in: path
        name: shopId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.QueryVoucherOfShopResp'
      summary: 查询店铺的优惠券列表
      tags:
      - voucher
  /voucher/seckill:
    post:
      consumes:
      - application/json
      parameters:
      - description: 优惠券信息，包含秒杀信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Voucher'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.AddSeckillVoucherResp'
      summary: 新增秒杀券
      tags:
      - voucher
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
