services:
  mysql:
    image: mariadb
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=hmdp
    volumes:
      - ./hmdp.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass 123321" ]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis
      - mysql